spring.datasource.url=jdbc:oracle:thin:@187.8.12.142:1521:ORCL
spring.datasource.username=rm559533
spring.datasource.password=250396
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.sql.init.mode=never